### ISSUE TITLE
BIRT Increase shared memory space or java memory?

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#29]
I think that is what's causing BIRT to complain. Complex query but it only returns 5 rows.
Runs fine in DBeaver.

<img width="822" alt="image" src="https://github.com/user-attachments/assets/cb63c098-5048-4043-bdb9-35816522e0e3">

**Comment by Andrew0Hill** [comment]
I can try to fix this, can you give me the query you used so I can replicate?

**Comment by mgkahn** [comment]
This can wait. I need to read up on how to use BIRT. I know you have lots of Family LInkage work you are trying to complete before tomorrow. SQL file attached. 
[birt_HTN_ACC_ESH.sql.txt](https://github.com/user-attachments/files/17284494/birt_HTN_ACC_ESH.sql.txt)

**Comment by Andrew0Hill** [comment]
Had some time while queries are running, so took a look.

It looks like this was caused by too little shared memory being allocated to the Postgres container. I replicated the error, then added `shm_size: "1gb"` to the `docker-compose.yml` under the Postgres container, and I was able to produce the report successfully. 

I pushed the changed `docker-compose.yml`, let me know if it works for you.

**Comment by mgkahn** [comment]
Will test today.
Interesting that it was the PG container. The query ran successfully using DBeaver but not BIRT so I thought it would turn out to be the Desktop container or java heap memory for BIRT.

**Comment by Andrew0Hill** [comment]
Tried some larger queries with the increased shared memory limit, and am not having any issues. We can re-open if this issue reappears.
