### ISSUE TITLE
Unable to build GUI from scratch

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#34]
Given the issues with GTK using Debian:XFCE, I thought I would try building against Debian:Mate.
Changed $DOCKER_TAG_NAME in nurs6293_desktop/build_image.sh to "andrew2hill/nurs6293_desktop_mate" and attempted to run build_image.sh. See error. Deleted ARM64 builder so it had to be recreated and got same error.

I did make sure I had the latest committed version on GitHub before creating my test branch.

<img width="1183" alt="image" src="https://github.com/user-attachments/assets/268ee5bd-3e27-4dbb-af47-c3a4c1d999e0">

**Comment by Andrew0Hill** [comment]
What does your modified docker file look like? 

I commented out the first `FROM linuxserver/webtop...` and added

```Dockerfile
# The build-arm64 stage builds the arm64 image.
#FROM linuxserver/webtop:debian-xfce@sha256:aba019c83c77d62c76dc1ed19d0948c1e4316f3be34591e448cd94effb5d24c3 AS build-arm64
FROM linuxserver/webtop:debian-mate AS build-arm64
```

and mine is able to build using `./build_image --dev`.

You also need to comment out the `docker pull` from the launchDesktop.sh, otherwise the remote image will overwrite the local one you build.

Side note, MATE doesn't have the BIRT issue, and I like the look better than XFCE, so if you're OK with it we can just switch over to MATE.

**Comment by mgkahn** [comment]
Ugh. I did not put in the "as ......" even though I know why it is needed.....
Let's go with MATE. I'll tell Toan to stop recording..........
LMK when you have updated the image using MATE on DockerHub.
