### ISSUE TITLE
Builder does not "build from scratch" as advertised

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#6]
docker-compose.yaml uses andrew2hill/nurs6293_desktop:latest image as starting point for webtop service.
There is no Dockerfile that builds andrew2hill/nurs6293_desktop.
(I wanted to rebuild webtop service with MATE for testing)

**Comment by Andrew0Hill** [comment]
The Dockerfile is in the `nurs6293_desktop` directory, you can run the `build_image.sh` script in the root of the repository to build the image.

The final command with the `--push` flag will likely fail for you since you don't have push capability to my repository (I can add if you'd like).

Alternatively, you can run the `pull_artifacts.sh` script to download the binary dependencies and then run your own docker build command. You should only need to replicate the process in the `build_image.sh` script if you want to build for both architectures simultaneously.

If you are just building and image for testing, you should be able to use a normal `docker build` command from inside the `nurs6293_desktop` directory.

**Comment by mgkahn** [comment]
@Andrew0Hill I see it now. I missed the Dockerfile in that folder. I only saw the YML file.
